name: Publish

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  release:
    types: [ published ]

jobs:
  publish:
    uses: iiasa/actions/.github/workflows/publish.yaml@main
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
